import { ExpandOneLevel, PickAny, ValuesUnionFromDict } from '../../../helpers/types'
import { DataFormat } from '../types'
import { DataType, NumSubType, StrSubType } from './dataType'
import { Fields } from './field'
import { ExtractOptionalRecordFieldNames, ExtractRequiredRecordFieldNames, _ToRecord } from './record'

/**
 * Extracts the field names from the given data format declaration that
 * are not auto-generated in some fashion, i.e. dateCreated fields, id fields,
 * uuid fields, and so on.
 */
export type ExtractAutoGeneratedFieldNames<TFields extends Fields> =
  Extract<
    ValuesUnionFromDict<TFields>,
    // Include datetime fields that default to current epoch
    { type: DataType.EPOCH, defaultToCurrentEpoch: true }
    // Include serial number fields (i.e. typically "id")
    | { type: DataType.NUM, subType: NumSubType.SERIAL }
    // Include string fields that default to an auto-generated uuid (i.e. v4uuid)
    | { type: DataType.STR, subType: StrSubType.UUID_V4, autoGenerate: true }
  >['name']

type ExtractExplicitExcludeInCreateOptionsFieldNames<TFields extends Fields> = Extract<
  ValuesUnionFromDict<TFields>,
  { excludeFromCreateOptions: true }
>['name']

/**
 * Extracts the field names from the given data format declaration that
 * have a defined default value.
 */
export type ExtractFieldNamesWithDefaults<TFields extends Fields> =
  Extract<ValuesUnionFromDict<TFields>, { default: any }>['name']

type CreateRecordOptionsFieldNames<TFields extends Fields> = Exclude<
  ValuesUnionFromDict<TFields>['name'],
  ExtractAutoGeneratedFieldNames<TFields> | ExtractExplicitExcludeInCreateOptionsFieldNames<TFields>
>

/**
 * Creates a type that can be used to create a record for the given data format declaration.
 *
 * This takes fields out of the standard record type that are auto-generated.
 */
type _CreateRecordOptions<TFields extends Fields> =
  // Required fields: don't have defaults
  PickAny<
    _ToRecord<TFields>,
    CreateRecordOptionsFieldNames<TFields> & ExtractRequiredRecordFieldNames<TFields>
  >
  // Optional fields: have defaults or allow null
  & Partial<
    PickAny<
      _ToRecord<TFields>,
      CreateRecordOptionsFieldNames<TFields> & ExtractOptionalRecordFieldNames<TFields>
    >
  >

export type CreateRecordOptions<TDataFormat extends DataFormat> = ExpandOneLevel<_CreateRecordOptions<TDataFormat['fields']>>

type _ManualCreateRecordOptions<TFields extends Fields> =
  // Pick auto-generated fields (optional)
  Partial<
    PickAny<
      _ToRecord<TFields>,
      ExtractAutoGeneratedFieldNames<TFields>
    >
  >
  // Pick fields with defaults (optional)
  & Partial<
    PickAny<
    _ToRecord<TFields>,
      ExtractFieldNamesWithDefaults<TFields>
    >
  >
  // Pick rest of fields (required)
  & Omit<
    _ToRecord<TFields>,
    ExtractAutoGeneratedFieldNames<TFields> | ExtractFieldNamesWithDefaults<TFields>
  >

export type ManualCreateRecordOptions<TDataFormat extends DataFormat> = _ManualCreateRecordOptions<TDataFormat['fields']>

export type CreateRecordFieldNames<TDataFormat extends DataFormat> = (keyof _CreateRecordOptions<TDataFormat['fields']>)[]
